---
version: '2'
services:
  pyload:
    image: pyload
    build: <REPODIR>
    container_name: pyload
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Baku
    volumes:
      - /path/to/appdata/config:/config
      - /root/data/pyload:/downloads
    ports:
      - 501:501 # Webinterface
      - 9666:9666 # Click 'N' Load
    restart: unless-stopped
